steps:
- id: 'build'
  name: 'gcr.io/cloud-builders/go'
  args: ['build', '-o', 'app', '.']
  env: ['PROJECT_ROOT=taxserver','CGO_ENABLED=0', 'GOOS=linux', 'GOARCH=amd64', 'GO111MODULE=on']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/taxserver', '.']
  waitFor: ['build']
images:
- 'gcr.io/$PROJECT_ID/taxserver'